/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datastruct_project;

import java.awt.event.KeyEvent;

/**
 *
 * @author Usman Ghani Mughal
 */
public class MaxHeap extends javax.swing.JFrame {
    static int size=32;
    int n;
    int arr[]=new int[size];
    /**
     * Creates new form MaxHeap
     */
    public MaxHeap() {
        initComponents();
        n=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        InsertArea = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        InsertTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        InsertButton = new javax.swing.JButton();
        TreeArea = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        l11 = new javax.swing.JLabel();
        l12 = new javax.swing.JLabel();
        l13 = new javax.swing.JLabel();
        l14 = new javax.swing.JLabel();
        l15 = new javax.swing.JLabel();
        TreeFull = new javax.swing.JLabel();
        l16 = new javax.swing.JLabel();
        l17 = new javax.swing.JLabel();
        l18 = new javax.swing.JLabel();
        l19 = new javax.swing.JLabel();
        l20 = new javax.swing.JLabel();
        l21 = new javax.swing.JLabel();
        l22 = new javax.swing.JLabel();
        l23 = new javax.swing.JLabel();
        l24 = new javax.swing.JLabel();
        l25 = new javax.swing.JLabel();
        l26 = new javax.swing.JLabel();
        l27 = new javax.swing.JLabel();
        l28 = new javax.swing.JLabel();
        l29 = new javax.swing.JLabel();
        l30 = new javax.swing.JLabel();
        l31 = new javax.swing.JLabel();
        BACK = new javax.swing.JButton();
        deleteTree = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DelText = new javax.swing.JTextField();
        EnterButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        InsertArea.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        jLabel1.setText("      Insertion");

        InsertTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertTextFieldActionPerformed(evt);
            }
        });
        InsertTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                InsertTextFieldKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        jLabel2.setText("Enter Number Here : ");

        InsertButton.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        InsertButton.setText("Press Enter");
        InsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButtonActionPerformed(evt);
            }
        });
        InsertButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                InsertButtonKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout InsertAreaLayout = new javax.swing.GroupLayout(InsertArea);
        InsertArea.setLayout(InsertAreaLayout);
        InsertAreaLayout.setHorizontalGroup(
            InsertAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertAreaLayout.createSequentialGroup()
                .addGroup(InsertAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(InsertAreaLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(InsertTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InsertAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(InsertAreaLayout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(InsertAreaLayout.createSequentialGroup()
                            .addGap(89, 89, 89)
                            .addComponent(InsertButton))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        InsertAreaLayout.setVerticalGroup(
            InsertAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(InsertAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InsertTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InsertButton)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        TreeArea.setBackground(new java.awt.Color(255, 255, 255));

        l1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        l1.setBorder(new javax.swing.border.MatteBorder(null));

        l2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        l2.setBorder(new javax.swing.border.MatteBorder(null));

        l3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        l3.setBorder(new javax.swing.border.MatteBorder(null));

        l4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        l4.setBorder(new javax.swing.border.MatteBorder(null));

        l5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        l5.setBorder(new javax.swing.border.MatteBorder(null));

        l6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        l6.setBorder(new javax.swing.border.MatteBorder(null));

        l7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        l7.setBorder(new javax.swing.border.MatteBorder(null));

        l8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        l8.setBorder(new javax.swing.border.MatteBorder(null));

        l9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        l9.setBorder(new javax.swing.border.MatteBorder(null));

        l10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        l10.setBorder(new javax.swing.border.MatteBorder(null));

        l11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        l11.setBorder(new javax.swing.border.MatteBorder(null));

        l12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        l12.setBorder(new javax.swing.border.MatteBorder(null));

        l13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        l13.setBorder(new javax.swing.border.MatteBorder(null));

        l14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        l14.setBorder(new javax.swing.border.MatteBorder(null));

        l15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        l15.setBorder(new javax.swing.border.MatteBorder(null));

        TreeFull.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        TreeFull.setBorder(new javax.swing.border.MatteBorder(null));

        l16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        l16.setBorder(new javax.swing.border.MatteBorder(null));

        l17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        l17.setBorder(new javax.swing.border.MatteBorder(null));

        l18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        l18.setBorder(new javax.swing.border.MatteBorder(null));

        l19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        l19.setBorder(new javax.swing.border.MatteBorder(null));

        l20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        l20.setBorder(new javax.swing.border.MatteBorder(null));

        l21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        l21.setBorder(new javax.swing.border.MatteBorder(null));

        l22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        l22.setBorder(new javax.swing.border.MatteBorder(null));

        l23.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        l23.setBorder(new javax.swing.border.MatteBorder(null));

        l24.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        l24.setBorder(new javax.swing.border.MatteBorder(null));

        l25.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        l25.setBorder(new javax.swing.border.MatteBorder(null));

        l26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        l26.setBorder(new javax.swing.border.MatteBorder(null));

        l27.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        l27.setBorder(new javax.swing.border.MatteBorder(null));

        l28.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        l28.setBorder(new javax.swing.border.MatteBorder(null));

        l29.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        l29.setBorder(new javax.swing.border.MatteBorder(null));

        l30.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        l30.setBorder(new javax.swing.border.MatteBorder(null));

        l31.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        l31.setBorder(new javax.swing.border.MatteBorder(null));

        BACK.setBackground(new java.awt.Color(102, 102, 102));
        BACK.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        BACK.setForeground(new java.awt.Color(0, 0, 0));
        BACK.setText("Back");
        BACK.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TreeAreaLayout = new javax.swing.GroupLayout(TreeArea);
        TreeArea.setLayout(TreeAreaLayout);
        TreeAreaLayout.setHorizontalGroup(
            TreeAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TreeAreaLayout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(l8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(l9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(l11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(l12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(l13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(l14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(TreeAreaLayout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208)
                .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(TreeAreaLayout.createSequentialGroup()
                .addGroup(TreeAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TreeAreaLayout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(l10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TreeAreaLayout.createSequentialGroup()
                        .addGroup(TreeAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TreeAreaLayout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(l16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(l17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(l18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(l19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l20, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TreeAreaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(l4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116)))
                        .addGroup(TreeAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(TreeAreaLayout.createSequentialGroup()
                                .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(l6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(TreeAreaLayout.createSequentialGroup()
                                .addComponent(l22, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l23, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l26, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l27, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l28, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l29, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TreeAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TreeAreaLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(l30, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(l31, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TreeAreaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TreeAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TreeAreaLayout.createSequentialGroup()
                        .addComponent(l15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TreeAreaLayout.createSequentialGroup()
                        .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(376, 376, 376))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TreeAreaLayout.createSequentialGroup()
                        .addComponent(TreeFull, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BACK, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        TreeAreaLayout.setVerticalGroup(
            TreeAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TreeAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(TreeAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TreeAreaLayout.createSequentialGroup()
                        .addGroup(TreeAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(l4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TreeAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TreeAreaLayout.createSequentialGroup()
                        .addGap(0, 37, Short.MAX_VALUE)
                        .addGroup(TreeAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TreeAreaLayout.createSequentialGroup()
                                .addComponent(l17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(146, 146, 146))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TreeAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(TreeAreaLayout.createSequentialGroup()
                                    .addComponent(l16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(146, 146, 146))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TreeAreaLayout.createSequentialGroup()
                                    .addGroup(TreeAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(l30, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(l31, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(TreeAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(BACK, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(TreeFull, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addContainerGap()))))
                    .addGroup(TreeAreaLayout.createSequentialGroup()
                        .addGroup(TreeAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TreeAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(l13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(TreeAreaLayout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(l10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(l9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(l8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(l11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(l15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(TreeAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        deleteTree.setBackground(new java.awt.Color(51, 102, 255));

        jLabel3.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        jLabel3.setText("Deletion");

        jLabel4.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        jLabel4.setText("Enter Number Here : ");

        DelText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelTextActionPerformed(evt);
            }
        });
        DelText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DelTextKeyPressed(evt);
            }
        });

        EnterButton.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        EnterButton.setText("Press Enter");
        EnterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deleteTreeLayout = new javax.swing.GroupLayout(deleteTree);
        deleteTree.setLayout(deleteTreeLayout);
        deleteTreeLayout.setHorizontalGroup(
            deleteTreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteTreeLayout.createSequentialGroup()
                .addGroup(deleteTreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deleteTreeLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel3))
                    .addGroup(deleteTreeLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DelText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(deleteTreeLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(EnterButton)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        deleteTreeLayout.setVerticalGroup(
            deleteTreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteTreeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(deleteTreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(EnterButton)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 0));
        jLabel5.setText("   MAX TREE");

        jLabel6.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 0));
        jLabel6.setText("    HEAP");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(InsertArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(deleteTree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TreeArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(InsertArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(deleteTree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addComponent(TreeArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertTextFieldActionPerformed
        
            int num=Integer.parseInt(InsertTextField.getText());
        this.insert(num,n);
        InsertTextField.setText("");
        
    }//GEN-LAST:event_InsertTextFieldActionPerformed

    private void InsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButtonActionPerformed
        
        int num=Integer.parseInt(InsertTextField.getText());
        this.insert(num,n);
        InsertTextField.setText("");
    }//GEN-LAST:event_InsertButtonActionPerformed

    private void EnterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterButtonActionPerformed
      
        int num=Integer.parseInt(DelText.getText());
       this.delete(num);
       DelText.setText("");  
        
    }//GEN-LAST:event_EnterButtonActionPerformed

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
        new Main_Frame().setVisible(true);
        this.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_BACKActionPerformed

    private void InsertTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InsertTextFieldKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            int num=Integer.parseInt(InsertTextField.getText());
        this.insert(num,n);
        InsertTextField.setText("");
        }
    }//GEN-LAST:event_InsertTextFieldKeyPressed

    private void InsertButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InsertButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertButtonKeyPressed

    private void DelTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DelTextKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER)
       {
           int num=Integer.parseInt(DelText.getText());
       this.delete(num);
       DelText.setText("");  
       }
    }//GEN-LAST:event_DelTextKeyPressed

    private void DelTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DelTextActionPerformed
    void del_last(int n)
    {
           switch(n)
           {
               case 0:
               {
                   l1.setText(" ");
                   
                   break;
               }
               case 1:
               {
                   l2.setText(" ");
                   break;
               }
               case 2:
               {
                   l3.setText(" ");
                   break;
               }
               case 3:
               {
                   l4.setText(" ");
                   break;
               }
               case 4:
               {
                   l5.setText(" ");
                   break;
               }
               case 5:
               {
                   l6.setText(" ");
                   break;
               }
               case 6:
               {
                   l7.setText(" ");
                   break;
               }
               case 7:
               {
                   l8.setText(" ");
                   break;
               }
               case 8:
               {
                   l9.setText(" ");
                   break;
               }
               case 9:
               {
                   l10.setText(" ");
                   break;
               }
               case 10:
               {
                   l11.setText(" ");
                   break;
               }
               case 11:
               {
                   l12.setText(" ");
                   break;
               }
               case 12:
               {
                   l13.setText(" ");
                   break;
               }
               case 13:
               {
                   l14.setText(" ");
                   break;
               }
               case 14:
               {
                   l15.setText(" ");
                   break;
               }
               case 15:
               {
                   l16.setText(" ");
                   break;
               }
               case 16:
               {
                   l17.setText(" ");
                   break;
               }
               case 17:
               {
                   l18.setText(" ");
                   break;
               }
               case 18:
               {
                   l19.setText(" ");
                   break;
               }
               case 19:
               {
                   l20.setText(" ");
                   break;
               }
               case 20:
               {
                   l21.setText(" ");
                   break;
               }
               case 21:
               {
                   l22.setText(" ");
                   break;
               }
               case 22:
               {
                   l23.setText(" ");
                   break;
               }
               case 23:
               {
                   l24.setText(" ");
                   break;
               }
               case 124:
               {
                   l25.setText(" ");
                   break;
               }
               case 25:
               {
                   l26.setText(" ");
                   break;
               }
               case 26:
               {
                   l27.setText(" ");
                   break;
               }
               case 27:
               {
                   l28.setText(" ");
                   break;
               }
               case 28:
               {
                   l29.setText(" ");
                   break;
               }
               case 29:
               {
                   l30.setText(" ");
                   break;
               }
               case 30:
               {
                   l31.setText(" ");
                   break;
               }
               default:
               {
                   TreeFull.setText("Tree is FULL");
                   break;
               }
           }
           
       
    }
    public void delete(int num)
    {
        int left,right,temp,par,i;
        for(i=0;i<n;i++)
        {
            if(num==this.arr[i])
            {
                break;
            }
        }
        if(num!=this.arr[i])
        {
          //  TreeFull.setText("Number is not Present in the Heap");
            new Error().setVisible(true);
            return;
        }
        this.arr[i]=this.arr[n-1];
        this.display(n);
        this.del_last(n-1);
        n--;
        par=(i-1)/2;
        if(this.arr[i]>this.arr[par])
        {
            this.insert(this.arr[i],i);
            return;
        }
        left=2*i+1;
        right=2*i+2;
        while(right<n)
        {
            if(this.arr[i]>=this.arr[left]&&this.arr[i]>=this.arr[right])
            {
                return;
            }
            if(this.arr[right]<=this.arr[left])
            {
                temp=arr[i];
                arr[i]=arr[left];
                this.arr[left]=temp;
                i=left;
                this.display(n);
            }
            else
            {
                temp=arr[i];
                arr[i]=arr[right];
                this.arr[right]=temp;
                i=right;
                this.display(n);
            }
            left=2*i+1;
            right=2*i+2;
        }
        if(left==n-1&&this.arr[i]<this.arr[left])
        {
            temp=this.arr[i];
            this.arr[i]=this.arr[left];
            this.arr[left]=temp;
            this.display(n);
        }
    }
    public void insert(int num,int loc)
    {
        int par;
        while(loc>0)
        {
            par=(loc-1)/2;
            if(num<=this.arr[par])
            {
                this.arr[loc]=num;
                n++;
                this.display(n);
                return;
            }
            this.arr[loc]=this.arr[par];
            loc=par;
        }
        this.arr[0]=num;
        this.arr[loc]=num;
        n++;
        this.display(n);   
    }
    public void display(int n)
    {
        int i,z;
        if(n==0)
       {
           System.out.println("Heap is Empty");
           return;
       }
       for(i=0;i<n;i++)
       {
           switch(i)
           {
               case 0:
               {
                   l1.setText(Integer.toString(this.arr[i]));
                   
                   break;
               }
               case 1:
               {
                   l2.setText(Integer.toString(this.arr[i]));
                   break;
               }
               case 2:
               {
                   l3.setText(Integer.toString(this.arr[i]));
                   break;
               }
               case 3:
               {
                   l4.setText(Integer.toString(this.arr[i]));
                   break;
               }
               case 4:
               {
                   l5.setText(Integer.toString(this.arr[i]));
                   break;
               }
               case 5:
               {
                   l6.setText(Integer.toString(this.arr[i]));
                   break;
               }
               case 6:
               {
                   l7.setText(Integer.toString(this.arr[i]));
                   break;
               }
               case 7:
               {
                   l8.setText(Integer.toString(this.arr[i]));
                   break;
               }
               case 8:
               {
                   l9.setText(Integer.toString(this.arr[i]));
                   break;
               }
               case 9:
               {
                   l10.setText(Integer.toString(this.arr[i]));
                   break;
               }
               case 10:
               {
                   l11.setText(Integer.toString(this.arr[i]));
                   break;
               }
               case 11:
               {
                   l12.setText(Integer.toString(this.arr[i]));
                   break;
               }
               case 12:
               {
                   l13.setText(Integer.toString(this.arr[i]));
                   break;
               }
               case 13:
               {
                   l14.setText(Integer.toString(this.arr[i]));
                   break;
               }
               case 14:
               {
                   l15.setText(Integer.toString(this.arr[i]));
                   break;
               }
               case 15:
               {
                   l16.setText(Integer.toString(this.arr[i]));
                   break;
               }
               case 16:
               {
                   l17.setText(Integer.toString(this.arr[i]));
                   break;
               }
               case 17:
               {
                   l18.setText(Integer.toString(this.arr[i]));
                   break;
               }
               case 18:
               {
                   l19.setText(Integer.toString(this.arr[i]));
                   break;
               }
               case 19:
               {
                   l20.setText(Integer.toString(this.arr[i]));
                   break;
               }
               case 20:
               {
                   l21.setText(Integer.toString(this.arr[i]));
                   break;
               }
               case 21:
               {
                   l22.setText(Integer.toString(this.arr[i]));
                   break;
               }
               case 22:
               {
                   l23.setText(Integer.toString(this.arr[i]));
                   break;
               }
               case 23:
               {
                   l24.setText(Integer.toString(this.arr[i]));
                   break;
               }
               case 124:
               {
                   l25.setText(Integer.toString(this.arr[i]));
                   break;
               }
               case 25:
               {
                   l26.setText(Integer.toString(this.arr[i]));
                   break;
               }
               case 26:
               {
                   l27.setText(Integer.toString(this.arr[i]));
                   break;
               }
               case 27:
               {
                   l28.setText(Integer.toString(this.arr[i]));
                   break;
               }
               case 28:
               {
                   l29.setText(Integer.toString(this.arr[i]));
                   break;
               }
               case 29:
               {
                   l30.setText(Integer.toString(this.arr[i]));
                   break;
               }
               case 30:
               {
                   l31.setText(Integer.toString(this.arr[i]));
                   break;
               }
               default:
               {
                   TreeFull.setText("Tree is FULL");
                   break;
               }
           }
           
       }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MaxHeap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MaxHeap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MaxHeap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MaxHeap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MaxHeap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BACK;
    public javax.swing.JTextField DelText;
    public javax.swing.JButton EnterButton;
    private javax.swing.JPanel InsertArea;
    public javax.swing.JButton InsertButton;
    public javax.swing.JTextField InsertTextField;
    private javax.swing.JPanel TreeArea;
    public javax.swing.JLabel TreeFull;
    private javax.swing.JPanel deleteTree;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel l1;
    public javax.swing.JLabel l10;
    public javax.swing.JLabel l11;
    public javax.swing.JLabel l12;
    public javax.swing.JLabel l13;
    public javax.swing.JLabel l14;
    public javax.swing.JLabel l15;
    public javax.swing.JLabel l16;
    public javax.swing.JLabel l17;
    public javax.swing.JLabel l18;
    public javax.swing.JLabel l19;
    public javax.swing.JLabel l2;
    public javax.swing.JLabel l20;
    public javax.swing.JLabel l21;
    public javax.swing.JLabel l22;
    public javax.swing.JLabel l23;
    public javax.swing.JLabel l24;
    public javax.swing.JLabel l25;
    public javax.swing.JLabel l26;
    public javax.swing.JLabel l27;
    public javax.swing.JLabel l28;
    public javax.swing.JLabel l29;
    public javax.swing.JLabel l3;
    public javax.swing.JLabel l30;
    public javax.swing.JLabel l31;
    public javax.swing.JLabel l4;
    public javax.swing.JLabel l5;
    public javax.swing.JLabel l6;
    public javax.swing.JLabel l7;
    public javax.swing.JLabel l8;
    public javax.swing.JLabel l9;
    // End of variables declaration//GEN-END:variables
}
